#=======================================================================================================================
# https://github.com/ophub/op
# Description: Automatically delete older releases
# Function: Delete older releases
# Cron: min (0 - 59) / hour (0 - 23) / day of month (1 - 31) / month (1 - 12) / day of week (0 - 6)(Sunday - Saturday)
#=======================================================================================================================

name: Delete older releases and artifacts

on:
  repository_dispatch:
  workflow_dispatch:
  #release:
    #types: published
  #push:
    #branches:
      #- main
    #paths:
      #- '.github/workflows/delete-older-releases-artifacts.yml'
  schedule:
    - cron: '30 23 * * 0'

env:
  DELETE_RELEASE: true
  DELETE_ARTIFACTS: true
  RECENT_LASTEST: 30

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Delete older releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      if: env.DELETE_RELEASE == 'true'
      with:
        keep_latest: ${{ env.RECENT_LASTEST }}
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

